const PAYMENT_STATUSES = Object.freeze({
    PENDING: "PENDING",
    STK_INITIATED: "STK_INITIATED",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED"
});

const TERMINAL_PAYMENT_STATUSES = [
    PAYMENT_STATUSES.SUCCESS,
    PAYMENT_STATUSES.FAILED,
    PAYMENT_STATUSES.CANCELLED,
    PAYMENT_STATUSES.REFUNDED
];

module.exports = {
    PAYMENT_STATUSES,
    TERMINAL_PAYMENT_STATUSES
};
